import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  containerPrincipal: {
    flex: 1,
    borderRadius: 40,
    paddingHorizontal: 2,
    margintop: 90,
    paddingTop: 50,
  },

  container: {
    backgroundColor: "rgba(30, 35, 40, 0.5)",
    flex: 1,
    paddingHorizontal: 10,
    paddingTop: 32,
    borderColor: "rgba(10, 20, 40, 0.5)",
    borderRadius: 50,
    marginHorizontal: 2,
  },
  containerDark: {
    flex: 1,
    paddingHorizontal: 10,
    paddingTop: 32,
    borderColor: "rgba(10, 20, 40, 0.5)",
    backgroundColor: "rgba(0, 0, 0,0.5)",
    marginHorizontal: 2,
    borderRadius: 50,
  },

  topArea: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "space-between",
    top: 0,
    borderRadius: 20,
    margintop: 0,
  },

  backgroundImage: {
    flex: 1,
    resizeMode: "cover",
    position: "absolute",
    width: "100%",
    height: "100%",
    top: -20,
  },

  topText: {
    fontSize: 14,
    fontWeight: "400",
    textAlign: "center",
    marginRight: 20,
    top: 20,
    color: "#FFFFFF",
  },
  topTextDark: {
    fontSize: 14,
    fontWeight: "400",
    textAlign: "center",
    top: 20,
    color: "#FFD700",
  },
  topText1: {
    fontSize: 12,
    fontWeight: "bold",
    textAlign: "center",
    top: 0,
    color: "#FFFFFF",
  },
  topTextDark1: {
    fontSize: 12,
    fontWeight: "bold",
    textAlign: "center",
    top: 0,
    color: "#FFD700",
  },
  topImage: {
    width: 220,
    height: 110,
    marginLeft: 68,
    margin: 0,
  },

  championItem: {
    flex: 1,
    alignItems: "center",
    marginBottom: 16,
    borderWidth: 3,
    borderLeftWidth: 0,
    borderRightWidth: 0,
    borderColor: "rgba( 30, 35, 40, 1)",
  },
  favoriteStar: {
    width: 20,
    height: 20,
    zIndex: 1,
    top: 3,
    right: 5,
    alignSelf: "flex-end",
    position: "absolute",
  },
  championImage: {
    width: 100,
    height: 100,
    resizeMode: "contain",
  },
  championName: {
    backgroundColor: "rgba(10, 20, 40, 0.5)",
    width: 96.7,
    height: 25,
    fontSize: 13,
    fontWeight: "400",
    color: "#C89B3C",
    textAlign: "center",
    borderWidth: 2,
    borderRightWidth: 1,
    borderLeftWidth: 1,
    borderColor: "black",
    justifyContent: "center",
    alignItems: "center",
  },
});
